import numpy as np
import matplotlib.pyplot as plt
from task1_1 import weightedAdj as W
from task1_2 import phi_parabola, logistic_grad, generate_dataset

G=6
P=40 + (G % 3) * 10
def split_dataset_even_groups(X, y, N_agents,P, G, seed=42):
    """
    Divide il dataset in N subsets per i gruppi PARI (Even Groups).
    - Mantiene P% dei dati come Baseline Random (divisa equamente).
    - Il restante (100-P)% viene ordinato per la feature x2 e diviso in blocchi contigui.
    """
    rng = np.random.default_rng(seed)
    M = len(X)
    # 1. Calcolo percentuale P
    num_baseline = int(M * (P / 100))
    print(f"Group {G}: P = {P}%. Baseline points: {num_baseline}, Remaining points: {M - num_baseline}")
    
    # 2. Creiamo un array di indici da 0 a M-1 e lo mescoliamo
    indices = np.arange(M)
    rng.shuffle(indices)
    
    # Separiamo gli indici per la baseline e per il resto
    idx_baseline = indices[:num_baseline]
    idx_remaining = indices[num_baseline:]
    # Dividiamo gli indici della baseline equamente tra gli N agenti
    baseline_splits = np.array_split(idx_baseline, N_agents)
    
    # 3. Vertical Feature-Biased Split sul (100-P)% rimanente
    # Estraiamo i valori della feature x2 (seconda colonna, indice 1) per i dati rimanenti
    x2_remaining = X[idx_remaining, 1]
    
    # np.argsort restituisce l'ordine degli indici per avere l'array crescente
    sorted_order = np.argsort(x2_remaining)
    idx_remaining_sorted = idx_remaining[sorted_order]
    
    # Dividiamo gli indici ordinati in N blocchi contigui
    sorted_splits = np.array_split(idx_remaining_sorted, N_agents)
    
    # 4. Uniamo le due parti per ciascun agente
    agent_data = {}
    for i in range(N_agents):
        # Concateniamo la sua porzione di baseline e la sua porzione del blocco ordinato
        agent_final_indices = np.concatenate((baseline_splits[i], sorted_splits[i]))
        
        # Salviamo X e y per questo agente
        agent_data[i] = {
            'X': X[agent_final_indices],
            'y': y[agent_final_indices]
        }
        
    return agent_data

# ==========================================
# ESEMPIO DI UTILIZZO E TEST
# ==========================================
if __name__ == "__main__":
    G = 6       # Group number
    N = 5      # Number of agents
    M = 500     # Dataset size
    
    # Generiamo un dataset fittizio (sostituisci col tuo generate_dataset)
    rng = np.random.default_rng(99)
    w_true = rng.standard_normal(3) # 3 for Parabola
    b_true = rng.uniform(-0.5, 0.5)
    X, y = generate_dataset(M, w_true, b_true, phi_parabola)
    # Chiamiamo la funzione di split
    agents = split_dataset_even_groups(X, y, N, G)

    # Assuming 'weightedAdj' from task1_1.py is available as 'W'
    # Assuming 'logistic_grad' and 'phi_parabola' from task1_2.py are imported
    # Assuming 'agents' dictionary is generated by your split_dataset_even_groups function

                  # Number of agents
    q = 3                   # For Parabola mapping: [x1, x2, x1^2]
    d = q + 1               # Number of optimization variables [w; b]
    max_iter = 2000
    stepsize = 0.05

    # 1. Initialize variables
    z = np.zeros((N, d))         # Current weights for each agent
    s = np.zeros((N, d))         # Tracking variable for each agent
    grad_old = np.zeros((N, d))  # Store previous gradients

    # Pre-compute Phi for each agent to save time in the loop
    for i in range(N):
        agents[i]['Phi'] = phi_parabola(agents[i]['X'])

    # 2. Initial Gradient computation
    for i in range(N):
        # Calculate gradient of logistic loss on Agent i's local data
        grad_old[i] = logistic_grad(z[i], agents[i]['Phi'], agents[i]['y'])
        s[i] = grad_old[i].copy()
    cost_history = []
    consensus_history = []

    # 3. Distributed Gradient Tracking Loop
    for k in range(max_iter):
        
        # --- UPDATE z ---
        # z^{k+1} = W * z^k - alpha * s^k
        # W @ z implicitly does the neighbor summation you did with loops in task1_1
        z_new = W @ z - stepsize * s
        
        grad_new = np.zeros((N, d))
        total_cost = 0
        # --- COMPUTE NEW LOCAL GRADIENTS ---
        for i in range(N):
            grad_new[i] = logistic_grad(z_new[i], agents[i]['Phi'], agents[i]['y'])
            # Optional: compute local loss to track total cost
            # total_cost += logistic_loss(z_new[i], agents[i]['Phi'], agents[i]['y'])
            
        # --- UPDATE s ---
        # s^{k+1} = W * s^k + grad_new - grad_old
        s_new = W @ s + grad_new - grad_old
        
        # --- PREPARE FOR NEXT ITERATION ---
        z = z_new
        s = s_new
        grad_old = grad_new
        
        # Track metrics
        # cost_history.append(total_cost)
        # consensus_error = np.linalg.norm(z - np.mean(z, axis=0))
        # consensus_history.append(consensus_error)

    # The final centralized model can be estimated as the mean of all agents' weights
    final_wb = np.mean(z, axis=0)